name: Deploy React App to Azure VM

on:
  push:
    branches:
      - main  # Change to your deployment branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18  # Ensure compatibility with Vite

    - name: Install dependencies and build
      run: |
        npm install
        npm run build

    - name: Deploy to Azure VM
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USER }}
        key: ${{ secrets.AZURE_SSH_KEY }}
        port: 22
        script: |
          rm -rf /var/www/html/*
          mkdir -p /tmp/build
          exit

    - name: Upload build files to Azure VM
      uses: appleboy/scp-action@v1.0.0
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USER }}
        key: ${{ secrets.AZURE_SSH_KEY }}
        source: "dist/*"
        target: "/var/www/html/"

    - name: Restart Nginx
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USER }}
        key: ${{ secrets.AZURE_SSH_KEY }}
        script: |
          sudo systemctl restart nginx
